### ISSUE TITLE
NoMethodError: undefined method `type' for nil:NilClass

### ISSUE THREAD

**Issue by edestecd** [voxpupuli/puppet-lint-absolute_classname-check#12]
Getting this now after updating to hiera 5 lookup function everywhere:
```
NoMethodError: undefined method `type' for nil:NilClass
/usr/local/rvm/gems/ruby-2.1.10@puppet/gems/puppet-lint-absolute_classname-check-0.2.4/lib/puppet-lint/plugins/check_absolute_classname.rb:6:in `block in check'
/usr/local/rvm/gems/ruby-2.1.10@puppet/gems/puppet-lint-absolute_classname-check-0.2.4/lib/puppet-lint/plugins/check_absolute_classname.rb:3:in `each'
/usr/local/rvm/gems/ruby-2.1.10@puppet/gems/puppet-lint-absolute_classname-check-0.2.4/lib/puppet-lint/plugins/check_absolute_classname.rb:3:in `each_with_index'
/usr/local/rvm/gems/ruby-2.1.10@puppet/gems/puppet-lint-absolute_classname-check-0.2.4/lib/puppet-lint/plugins/check_absolute_classname.rb:3:in `check'
```

**Comment by alexjfisher** [comment]
0.2.5 has been released including this fix.
